# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:34:14+00:00

from __future__ import annotations

from enum import Enum


class GeometriesZoom(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16
    integer_17 = 17
    integer_18 = 18
    integer_19 = 19
    integer_20 = 20
    integer_21 = 21
    integer_22 = 22


class VersionNumber(Enum):
    integer_2 = 2


class Ext(Enum):
    json = 'json'


class View(Enum):
    Unified = 'Unified'
    IN = 'IN'
    PK = 'PK'
    IL = 'IL'
    MA = 'MA'


class Ext1(Enum):
    json = 'json'
    jsonp = 'jsonp'
    js = 'js'
    xml = 'xml'
