# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:34:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class GeometryListItem(BaseModel):
    position: Optional[str] = None
    radius: Optional[int] = None
    type: Optional[str] = None
    vertices: Optional[List[str]] = None


class FieldExtPostRequest(BaseModel):
    geometryList: Optional[List[GeometryListItem]] = None
