# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:34:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Address(BaseModel):
    freeformAddress: Optional[str] = None


class Poi(BaseModel):
    name: Optional[str] = None


class Position(BaseModel):
    lat: Optional[float] = None
    lon: Optional[float] = None


class PoiListItem(BaseModel):
    address: Optional[Address] = None
    poi: Optional[Poi] = None
    position: Optional[Position] = None


class FieldExtPostRequest(BaseModel):
    poiList: Optional[List[PoiListItem]] = None
