# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:34:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Point(BaseModel):
    lat: Optional[float] = None
    lon: Optional[float] = None


class Route(BaseModel):
    points: Optional[List[Point]] = None


class FieldExtPostRequest(BaseModel):
    route: Optional[Route] = None
